version: '3.8'

services:
  todoist-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: todoist-mcp-server:latest
    container_name: todoist-mcp-server
    ports:
      - "8080:8080"
    environment:
      - TODOIST_API_KEY=${TODOIST_API_KEY}
      - PORT=8080
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge